version: "3"

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
