version: "3"

services:
  web:
    build: ./
    command: gunicorn event_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    network_mode: cloudbuild

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 8000:80
    depends_on:
      - web
    network_mode: cloudbuild

volumes:
  static_volume:

networks:
  default:
    external:
      name: cloudbuild
