runtime: python
env: flex
entrypoint: gunicorn -b :$PORT event_project.wsgi


beta_settings:
    cloud_sql_instances: steam-talent-277511:europe-west3:corvento-postgres

runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7