# Generated by Django 3.0.5 on 2020-04-10 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
