# Generated by Django 3.0.5 on 2020-04-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.URLField(default='http://35.157.172.14/api/events/list/'),
            preserve_default=False,
        ),
    ]
