# Generated by Django 3.0.5 on 2020-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='community',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
