# Generated by Django 3.0.5 on 2020-04-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0012_appuser_firebase_id'),
        ('main', '0009_event_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.AppUser'),
        ),
    ]
