# Generated by Django 3.0.5 on 2020-05-07 15:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200507_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
    ]
