# Generated by Django 3.0.5 on 2020-05-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200508_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='desc',
        ),
    ]
