# Generated by Django 3.0.5 on 2020-05-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_event_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='community',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=500),
        ),
    ]
