# Generated by Django 3.0.5 on 2020-05-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200509_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='community',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=1000),
        ),
    ]
