# Generated by Django 3.0.5 on 2020-04-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('data', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='notifications',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app_user.UserNotifications'),
            preserve_default=False,
        ),
    ]
