# Generated by Django 3.0.5 on 2020-04-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20200411_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='notifications',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.UserNotifications'),
        ),
    ]
