# Generated by Django 3.0.5 on 2020-04-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_auto_20200413_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
