# Generated by Django 3.0.5 on 2020-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_appuser_firebase_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='community',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
