# Generated by Django 3.0.5 on 2020-04-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_auto_20200423_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
