# Generated by Django 3.0.5 on 2020-04-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_auto_20200424_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
