# Generated by Django 3.0.5 on 2020-04-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0014_auto_20200424_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
