# Generated by Django 3.0.5 on 2020-05-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
