# Generated by Django 3.0.5 on 2020-05-03 10:54

from django.db import migrations, models
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0019_auto_20200502_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, upload_to='user_notification_images'),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='is_read',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='read_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='data',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
