# Generated by Django 3.0.5 on 2020-05-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0020_auto_20200503_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='notifications',
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.AppUser'),
        ),
    ]
