# Generated by Django 3.0.5 on 2020-05-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0021_auto_20200503_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotifications',
        ),
    ]
