# Generated by Django 3.0.5 on 2020-05-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
        ('app_user', '0022_delete_usernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='device',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice'),
        ),
    ]
