# Generated by Django 3.0.5 on 2020-05-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0023_appuser_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='device',
        ),
    ]
