# Generated by Django 3.0.5 on 2020-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0024_remove_appuser_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default='testgeneratedbyadmin@corvento.com', max_length=254),
            preserve_default=False,
        ),
    ]
